### ISSUE TITLE
Do you have plan to upload your project?

### ISSUE THREAD

**Issue by JuChanSeo** [desaixie/gait#1]
I saw your porject in the conference and I have interest about your project.
If you share your project, that wolud help me so much. 
Thanks.

**Comment by desaixie** [comment]
Hi, thanks for your interest. I am currently busy with another deadline and I will set up the website and release code in a month.

**Comment by JuChanSeo** [comment]
Hi, thanks for reply. I'm gonna wait for your project. Good luck for your work!

**Comment by JuChanSeo** [comment]
Hi, Its me again. 
Do you have a plan to update this page?

**Comment by desaixie** [comment]
Hopefully, I will be able to get to this next week

**Comment by desaixie** [comment]
Hi @JuChanSeo , the code for GAIT is uploaded. Happy new year!

**Comment by JuChanSeo** [comment]
Thank you very much! :)
